# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: home
    weight: 9
  - name: Bio
    parent: home
    url: /
    weight: 10
  - name: Papers
    parent: home
    url: /#papers
    weight: 11
  - name: Talks
    parent: home
    url: /#talks
    weight: 12
  - name: News
    parent: home
    url: /#news
    weight: 13
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Kompendium
    url: kompendium/
    weight: 40
